### PR TITLE
Add NSAppleMusicUsageDescription

### PR DESCRIPTION
**Pull request by VincentSit**
FYR: [NSAppleMusicUsageDescription](https://developer.apple.com/library/prerelease/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW47)

### CODE REVIEW

**Comment by VincentSit** [comment]
In addition you may need to update this SO [answer](http://stackoverflow.com/a/38650785/1644934) if you merge this PR.

**Comment by ChenYilong** [comment]
Thanks for your PR，but you'd better change your format ,you changed too much codehttps://github.com/ChenYilong/iOS10AdaptationTips/pull/2/files

**Comment by VincentSit** [comment]
The reason is I changed the indents to 4 tabs, the real changes only [three lines](https://github.com/ChenYilong/iOS10AdaptationTips/pull/2/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8).

You can add it yourself. I close this. Thank you.

**Comment by ChenYilong** [comment]
Done, https://github.com/ChenYilong/iOS10AdaptationTips/commit/9ae4e1e2509975fd702725584431c6394aca6286

**Comment by VincentSit** [comment]
Thank you!

**Pull request closed without merging**
